name: Bug Report
description: Report a problem with Angrier World Quests
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: ["gurligebis"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue with Angrier World Quests! Please fill out the details below so we can investigate.

  - type: dropdown
    id: game-variant
    attributes:
      label: Game Variant
      description: Which version of World of Warcraft are you playing?
      options:
        - Retail
    validations:
      required: true

  - type: input
    id: addon-version
    attributes:
      label: Addon Version
      description: "Which version of the addon are you using? (Format: [WoW Version]-[YYYYMMDD]-[Build])"
      placeholder: "e.g., 11.2.5-20251006-1"
    validations:
      required: true

  - type: input
    id: last-working-version
    attributes:
      label: Last Known Working Version
      description: "If applicable, which earlier version of the addon worked correctly?"
      placeholder: "e.g., 11.2.0-20250909-1"
    validations:
      required: false

  - type: textarea
    id: issue-description
    attributes:
      label: What happened?
      description: Describe the issue you are experiencing. What did you expect to happen?
      placeholder: "Explain the problem in detail"
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Please provide step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error
    validations:
      required: false

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any screenshots, error messages, or other details that might help.
      placeholder: "Paste screenshots, Lua errors, or logs here"
    validations:
      required: false
